openapi: '3.0.0'
info:
  version: 1.0.0
  title: SmartAssets
servers:
  - url: /api
paths:
  /:
    get:
      description: API home page
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    Error:
      required:
        - success
        - code
        - messages
        - errors
        - result
      properties:
        success:
          type: boolean
        code:
          type: integer
          format: int32
        messages:
          type: array
        errors:
          type: array

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key